### ISSUE TITLE
Username selection 

### ISSUE THREAD

**Issue by saitejakuruva** [SwachhApp/Swachh#10]
Have to discuss about the username will it be the phone number or we will be providing a way to create a username in our app? 
I think we should keep it simple username be both phone number/Email address something like this
![Screenshot 2019-10-06 at 5 37 43 PM](https://user-images.githubusercontent.com/20011410/66268943-21052300-e860-11e9-8938-8abe702c0397.png)

**Comment by sandipbhuyan** [comment]
Refer #3 for this

**Comment by sandipbhuyan** [comment]
Discussion is done for this issue I am putting it in low priority and closing this issue
